# Generated by Django 5.0.1 on 2024-03-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_name', models.CharField(max_length=100, verbose_name='RC_NAME')),
                ('rc_des', models.CharField(max_length=225, verbose_name='RC_description')),
            ],
        ),
        migrations.CreateModel(
            name='Add_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_no', models.CharField(max_length=100, verbose_name='Room_Number')),
                ('r_bed_no', models.CharField(max_length=100, verbose_name='Number_Of_Bed')),
                ('r_capacity', models.IntegerField(verbose_name='Room Capacity')),
                ('r_price', models.IntegerField(verbose_name='Price')),
                ('room_img', models.ImageField(blank=True, upload_to='img')),
                ('r_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelmgmtApp.room_cat')),
            ],
        ),
    ]
