# Generated by Django 5.0.1 on 2024-03-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelmgmtApp', '0001_initial'),
        ('UserApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('rating', models.CharField(max_length=256)),
                ('feedback_status', models.CharField(default=False, max_length=100, verbose_name='Feedback Status')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelmgmtApp.add_room')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
